### ISSUE TITLE
no .coffee and .jade versions

### ISSUE THREAD

**Issue by dillongreen** [ManuelDeLeon/viewmodel-docs#3]
The toggle from .js to .coffee and .html to .jade versions at http://viewmodel.meteor.com/#optionsBk --> Object Array - Single Selection doesn't work when the corresponding buttons are clicked.

**Comment by ManuelDeLeon** [comment]
I thought everyone hated CoffeeScript and Jade =D

What do you mean the toggle buttons don't work? I can switch from jade to html and coffee to js no problem...

**Comment by dillongreen** [comment]
Yes, works, but not for this one example (Object Array - Single Selection) and its code snippets (at least not for me). Let's not talk about the .coffee/.jade haters :)

**Comment by ManuelDeLeon** [comment]
Ahhh, okay I see it now. I'll fix it asap.

**Comment by ManuelDeLeon** [comment]
Done. Thanks for the heads up.

**Comment by dillongreen** [comment]
The 'Leaderboard Example' only has .js and .html in the explanation section i.e. it's not possible to toggle to .jade and .coffee versions.

Same goes for http://viewmodel.meteor.com/#bindBk and its friends. I guess I am just mentioning this because I prefer the less verbose versions of each... I am also someone who uses .styl rather than .css so... :)

Thanks anyway for this great great package, if it were for me, it would be in core and the standard way of doing things in meteor.
