### ISSUE TITLE
add more coffee and jade

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel-docs#4]
Is it too much to ask? - but I'd like when choosing coffee & jade as code source, other supplementary code sections like 'What's going on...' would also be displayed in the corresponding language.
Thanks!

**Comment by ManuelDeLeon** [comment]
As you can probably tell I love CoffeeScript and Jade but...

Dual documentation proved to be a bad idea after all. Creating and maintaining documentation is very hard as it is. Having it in two languages is twice the effort for little added value.

So for some sections, like bindings, I'll continue to provide examples in both but for other things I'll just stick to JavaScript.

**Comment by avalanche1** [comment]
I see. I just thought you had automatic code generation.

**Comment by avalanche1** [comment]
I've noticed, that js and html versions don't have bold formatting of code you wanted accentuated
