### ISSUE TITLE
add documentation how to modify vm methods

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel-docs#8]
If you have

``` coffee
vm = new ViewModel
   method: -> 'some code'
```

you cannot assign a new value to it with `@method 'some new value'`.
You have to overwrite it with `.extend` instead:

``` coffee
vm.extend
   method: 'some new value'
```

**Comment by ManuelDeLeon** [comment]
You're using it wrong.

``` cs
vm = new ViewModel
   method: -> 'some code'
```

In this case `method` is a function so when you do `vm.method("A")` it calls `method` with the parameter `"A"`.

When you do:

``` cs
vm.extend
   method: 'some new value'
```

ViewModel replaces the `method` function with a ViewModel property/function

**Comment by avalanche1** [comment]
What's the diff between `the method function` and `a ViewModel property/function`?

**Comment by ManuelDeLeon** [comment]
This method will always print the value given and return undefined:

``` cs
vm = new ViewModel
   printVal: (val) -> console.log(val)
```

In the following example the name value is automatically converted to a function that stores a value if called with a parameter (e.g. `vm.name("Alan")`) and returns the stored value if called without parameters (e.g. `vm.name()`).

``` cs
vm = new ViewModel
   name: ''
```

**Comment by avalanche1** [comment]
Yes, thats' totally in line with my 1st post: if you have a method, which is binded to some dom element, and then you need to give this element a new value (which might happen to be completely out of logic of the original method) - you'll have to substitute the method with a completely different property (but retaining original name), using `.extend`.
Like:

``` coffee
#initially
vm = new ViewModel
   me: 'Artem'
   status: (name) -> @me + " is married to " + name
vm.status('Kate')
vm.status('Mary')

#suddenly
vm.extend
   status: 'Unoccupied!'
```

**Comment by ManuelDeLeon** [comment]
I don't understand the problem.

``` cs
vm = new ViewModel
   me: 'Artem'
   status: (name) -> @me() + " is married to " + name

vm.status('Kate') # returns "Artem is married to Kate". As expected.
```

if you do:

``` cs
vm.extend
   status: 'Unoccupied!'
```

Then you're replacing status so now it now stores a value when called with a parameter and retrieves the stored value when called without a parameter. As expected.
